### ISSUE TITLE
Fix typo in the name of Ing. Lenka Kosková Třísková, Ph.D.

### ISSUE THREAD

**Issue by novakjak** [DanielADK/tul-bp#1]
The name in the document is written as Kostková while it should be Kosková. (Also maybe remove the dash joining the two surnames as it isn't written like that anywhere)
Source: https://www.fm.tul.cz/personal/lenka.koskova.triskova

**Comment by DanielADK** [comment]
fixed, thanks. Btw, usage of hyphen really depends on when the name was given (accordingly to the law) and of course country of origin. e.g. https://www.knihydobrovsky.cz/kniha/ondraskova-abeceda-661952, https://www.zakonyprolidi.cz/cs/2000-301
